version: '3.2'

networks:
  fabric:
    external:
      name: fabric
      
services: 
  serveur:
    image: inanimate/vsftpd-anon
    hostname: ftp
    volumes:
    # Shares
      - /nfs/fabric:/var/ftp
    read_only: true
    ports:
      - 20-21:20-21 
      - 65500-65515:65500-65515
    deploy:
      placement:
        constraints: [node.hostname ==multivac]
    networks:
      fabric:
        ipv4_address: 10.0.0.242
    